import type { Question } from "./cscs-data";

const q = (
  id: string,
  section: Question["section"],
  domain: Question["domain"],
  cognition: Question["cognition"],
  source: string,
  en: { prompt: string; options: [string, string, string]; explanation: string },
  zh: { prompt: string; options: [string, string, string]; explanation: string },
): Question => ({ id, section, domain, cognition, source, prompt: zh.prompt, options: zh.options, answer: en.options.findIndex((option) => option.startsWith("✓ ")), explanation: zh.explanation, en: { ...en, options: en.options.map((option) => option.replace(/^✓ /, "")) as [string, string, string] }, });

// Original, transformative items. The learner-supplied banks were used only to
// audit topic coverage and common distractor patterns; no purchased item is
// reproduced. English is canonical and every item is aligned to the 5th ed.
export const extendedQuestions: Question[] = [
  q("es07","科学基础","exercise-science","应用","Ch. 1 · note-bank coverage: sarcomere",
    {prompt:"During a concentric muscle action, which sarcomere change is expected?",options:["The A band shortens","✓ The I band and H zone narrow","The thick filaments shorten"],explanation:"Filaments slide rather than shorten. Greater overlap draws Z-lines closer, narrowing the I band and H zone while A-band length remains constant."},
    {prompt:"向心收缩时，肌节最可能发生哪种变化？",options:["A 带缩短","I 带与 H 区变窄","粗肌丝缩短"],explanation:"肌丝发生滑动而不是自身缩短。重叠增加使 Z 线靠近，I 带和 H 区变窄，而 A 带长度保持不变。"}),
  q("es08","科学基础","exercise-science","分析","Ch. 1 · note-bank coverage: cardiovascular",
    {prompt:"During progressive dynamic aerobic exercise, systolic pressure rises while diastolic pressure changes little. What best explains the diastolic response?",options:["Stroke volume has stopped","✓ Vasodilation in active tissue lowers peripheral resistance","Venous return falls to zero"],explanation:"Active-muscle vasodilation offsets much of the pressure effect of rising cardiac output, so diastolic pressure is often relatively stable."},
    {prompt:"递增动态有氧运动中，收缩压升高而舒张压变化较小。最佳解释是什么？",options:["每搏输出量已经停止","活动组织血管舒张降低外周阻力","静脉回流降为零"],explanation:"活动肌血管舒张会抵消心输出量上升的部分压力效应，因此舒张压通常相对稳定。"}),
  q("es09","科学基础","exercise-science","应用","Ch. 2 · Chinese bank coverage: torque",
    {prompt:"A dumbbell is held at the same elbow angle. Which change most reduces external elbow torque?",options:["Increase hand speed","✓ Move the load closer to the elbow","Co-contract the triceps harder"],explanation:"External torque equals force multiplied by the perpendicular moment arm. Moving the load closer shortens that moment arm."},
    {prompt:"在相同肘角度持哑铃时，哪项改变最能降低肘关节外部力矩？",options:["提高手部速度","让负荷更靠近肘关节","更强地共同收缩肱三头肌"],explanation:"外部力矩等于力乘以垂直力臂。负荷靠近肘关节会缩短力臂。"}),
  q("es10","科学基础","exercise-science","分析","Ch. 3 · English bank coverage: energy systems",
    {prompt:"A repeated-sprint session uses 6 seconds maximal work and 20 seconds rest. What is the most likely immediate limitation across repetitions?",options:["Complete absence of oxidative metabolism","✓ Incomplete phosphocreatine restoration","Loss of all muscle glycogen after repetition one"],explanation:"Short recovery does not fully restore phosphocreatine, so peak power falls even though glycolytic and oxidative contributions continue."},
    {prompt:"重复冲刺训练采用 6 秒全力与 20 秒休息。多次重复时最可能的即时限制是什么？",options:["氧化代谢完全不参与","磷酸肌酸恢复不完全","第一次后肌糖原全部耗尽"],explanation:"短休息无法完全恢复磷酸肌酸，因此峰值功率下降，同时糖酵解和氧化系统仍继续参与。"}),
  q("es11","科学基础","exercise-science","应用","Ch. 5 · Chinese bank coverage: early adaptation",
    {prompt:"A novice becomes stronger after four weeks with little measurable hypertrophy. Which adaptation best accounts for the gain?",options:["Hyperplasia","✓ Improved motor-unit recruitment and coordination","Conversion of every Type I fiber to Type II"],explanation:"Early strength gains are dominated by neural and skill adaptations before substantial hypertrophy becomes measurable."},
    {prompt:"初学者训练四周后力量提高，但几乎测不到肌肥大。哪种适应最能解释？",options:["肌纤维增生","运动单位募集和协调改善","所有 I 型纤维转化为 II 型"],explanation:"明显肌肥大出现前，早期力量增长主要来自神经与技术适应。"}),
  q("es12","科学基础","exercise-science","分析","Ch. 6 · English bank coverage: Fick equation",
    {prompt:"After endurance training, maximal oxygen uptake rises with both higher maximal cardiac output and greater extraction. Which equation organizes these changes?",options:["Power = force × velocity","✓ VO₂ = Q × a-vO₂ difference","MAP = SBP + DBP"],explanation:"The Fick equation links central oxygen delivery through cardiac output with peripheral oxygen extraction."},
    {prompt:"耐力训练后，最大摄氧量因最大心输出量与氧提取同时提高而上升。哪条公式组织这些变化？",options:["功率 = 力 × 速度","VO₂ = Q × 动静脉氧差","MAP = SBP + DBP"],explanation:"Fick 公式把心输出量代表的中枢氧输送与外周氧提取联系起来。"}),

  q("sp07","科学基础","sport-psychology","应用","Ch. 9 · English bank coverage: goal setting",
    {prompt:"Which goal is the best process goal for a weightlifter?",options:["Win the national title","Add 15 kg to the total by December","✓ Keep the bar close through every clean pull today"],explanation:"A process goal targets a controllable behavior performed now; titles are outcomes and future totals are performance goals."},
    {prompt:"对举重运动员而言，哪项最符合过程目标？",options:["赢得全国冠军","十二月前总成绩增加 15 kg","今天每次高翻拉起都让杠贴近身体"],explanation:"过程目标指向当下可控行为；冠军是结果目标，未来总成绩是表现目标。"}),
  q("sp08","科学基础","sport-psychology","分析","Ch. 9 · note-bank coverage: anxiety",
    {prompt:"Two athletes report the same high arousal before competition; one feels excited and the other threatened. What differs most directly?",options:["Their heart rate must differ","✓ Their cognitive interpretation of arousal","Only their aerobic fitness"],explanation:"Similar physiological arousal can be interpreted as facilitative excitement or debilitative threat, changing anxiety and performance."},
    {prompt:"两名运动员赛前唤醒程度同样很高；一人感到兴奋，另一人感到威胁。最直接的差异是什么？",options:["两人的心率必然不同","对唤醒的认知解释不同","只可能是有氧能力不同"],explanation:"相似的生理唤醒可被解释为促进性兴奋或削弱性威胁，从而影响焦虑和表现。"}),
  q("sp09","科学基础","sport-psychology","应用","Ch. 9 · Chinese bank coverage: reinforcement",
    {prompt:"A coach wants athletes to repeat effective landing mechanics. Which feedback best uses positive reinforcement?",options:["Ignore every correct attempt","Punish all errors with extra running","✓ Immediately recognize the specific quiet, aligned landing"],explanation:"Positive reinforcement adds a meaningful consequence after the desired behavior and should identify what was effective."},
    {prompt:"教练希望运动员重复有效落地技术。哪种反馈最符合正强化？",options:["忽略所有正确尝试","每次错误都罚跑","立即肯定具体的安静、对齐落地"],explanation:"正强化是在目标行为后增加有意义结果，并明确指出有效之处。"}),
  q("sp10","科学基础","sport-psychology","分析","Ch. 9 · official-practice coverage: attentional focus",
    {prompt:"During a complex lift, an athlete becomes overloaded by six simultaneous technical cues. What is the best immediate coaching change?",options:["Add more anatomical detail","✓ Use one short priority cue, preferably external when appropriate","Remove all feedback for the month"],explanation:"Working memory is limited. One prioritized cue reduces overload and often supports automatic movement control better than a list."},
    {prompt:"复杂举重动作中，运动员被六个同时出现的技术提示压垮。最好的即时调整是什么？",options:["增加更多解剖细节","只用一个简短优先提示，适合时采用外部焦点","整个月完全取消反馈"],explanation:"工作记忆容量有限。一个优先提示比长清单更能减少过载并支持自动控制。"}),
  q("sp11","科学基础","sport-psychology","应用","Ch. 9 · English bank coverage: imagery",
    {prompt:"Which imagery practice is most likely to transfer to a penalty kick?",options:["Imagining an unrelated vacation","✓ Rehearsing the kick from the athlete's perspective with timing and sensory detail","Watching a motivational film without rehearsal"],explanation:"Effective imagery is vivid, controllable, and functionally similar to the performance context."},
    {prompt:"哪种表象练习最可能迁移到点球表现？",options:["想象无关的度假场景","以运动员视角、真实节奏和感官细节排练射门","只看励志影片但不排练"],explanation:"有效表象应清晰、可控，并在功能上接近真实表现情境。"}),
  q("sp12","科学基础","sport-psychology","分析","Ch. 9 · note-bank coverage: referral",
    {prompt:"An athlete discloses persistent hopelessness and thoughts of self-harm. What is the strength coach's priority?",options:["Promise secrecy and continue training","Provide a clinical diagnosis","✓ Follow the emergency/referral protocol and connect the athlete with qualified help"],explanation:"Potential self-harm requires immediate safety action within policy and referral; it is outside the coach's clinical scope."},
    {prompt:"运动员透露长期绝望并有自伤想法。体能教练首先应该做什么？",options:["承诺保密并继续训练","给出临床诊断","按紧急/转介流程联系合格帮助"],explanation:"潜在自伤需要立即按制度处理安全与转介，超出体能教练的临床执业范围。"}),

  q("nu07","科学基础","nutrition","应用","Ch. 10 · Chinese bank coverage: energy balance",
    {prompt:"An athlete wants slow fat loss without sacrificing training quality. Which plan is most defensible?",options:["An extreme deficit and low protein","✓ A moderate deficit, adequate protein, resistance training, and performance monitoring","Eliminate all carbohydrate"],explanation:"A moderate, monitored deficit supports adherence and lean-mass retention better than an aggressive restriction."},
    {prompt:"运动员希望缓慢减脂且不牺牲训练质量。哪种计划最合理？",options:["极端热量缺口且低蛋白","适度缺口、足量蛋白、抗阻训练并监测表现","完全取消碳水"],explanation:"适度且受监测的热量缺口比激进限制更有利于坚持与保留瘦体重。"}),
  q("nu08","科学基础","nutrition","分析","Ch. 10 · English bank coverage: hydration",
    {prompt:"An athlete loses 1.4 kg, drinks 0.6 L, and produces no urine during a 2-hour session. Estimated sweat rate?",options:["0.4 L/h","0.7 L/h","✓ 1.0 L/h"],explanation:"Estimated sweat loss is 1.4 + 0.6 = 2.0 L; divided by two hours gives 1.0 L/h."},
    {prompt:"运动员两小时训练中减重 1.4 kg、饮水 0.6 L、无排尿。估算出汗率是多少？",options:["0.4 L/h","0.7 L/h","1.0 L/h"],explanation:"估算出汗量为 1.4 + 0.6 = 2.0 L；除以两小时得到 1.0 L/h。"}),
  q("nu09","科学基础","nutrition","应用","Ch. 11 · official-practice coverage: recovery",
    {prompt:"An athlete has another hard session in four hours after glycogen-depleting work. What deserves extra urgency?",options:["Delay all intake until dinner","✓ Begin carbohydrate, protein, fluid, and sodium recovery soon","Consume only fat"],explanation:"A short turnaround raises the value of early carbohydrate and fluid restoration plus protein for remodeling."},
    {prompt:"耗竭糖原训练后四小时还有一堂高强度训练。哪项恢复更紧迫？",options:["晚餐前完全不摄入","尽快补充碳水、蛋白质、液体和钠","只摄入脂肪"],explanation:"短恢复窗口提高了早期补充碳水、液体与蛋白质的价值。"}),
  q("nu10","科学基础","nutrition","分析","Ch. 11 · note-bank coverage: RED-S",
    {prompt:"Which pattern most strongly suggests low energy availability rather than normal training fatigue?",options:["One hard session","✓ Recurrent injury, impaired recovery, mood change, and menstrual/endocrine disruption","Temporary thirst after practice"],explanation:"A multisystem pattern involving health and performance raises concern for low energy availability and RED-S."},
    {prompt:"哪种表现最提示低能量可用性，而不是正常训练疲劳？",options:["一次高强度训练","反复伤病、恢复差、情绪变化及月经/内分泌异常","训练后短暂口渴"],explanation:"同时影响健康与表现的多系统表现提示低能量可用性和 RED-S 风险。"}),
  q("nu11","科学基础","nutrition","应用","Ch. 12 · English bank coverage: supplement screening",
    {prompt:"Before recommending an evidence-supported supplement, what should the coach verify next?",options:["The label color","✓ Effective dose, interactions, third-party testing, and sport rules","Whether a celebrity uses it"],explanation:"Evidence of potential benefit does not remove dose, contamination, interaction, or anti-doping risk."},
    {prompt:"推荐有证据支持的补剂前，教练下一步应核查什么？",options:["标签颜色","有效剂量、相互作用、第三方检测和项目规则","是否有明星使用"],explanation:"潜在有效证据不能消除剂量、污染、相互作用和反兴奋剂风险。"}),
  q("nu12","科学基础","nutrition","分析","Ch. 12 · Chinese bank coverage: scope",
    {prompt:"A coach is asked to treat an athlete's diagnosed iron-deficiency anemia with a supplement protocol. Best action?",options:["Prescribe a high dose independently","✓ Coordinate with the physician/dietitian and stay within scope","Ignore the diagnosis and increase conditioning"],explanation:"Diagnosed deficiency and therapeutic dosing belong with qualified medical/nutrition professionals; the coach supports the plan."},
    {prompt:"教练被要求用补剂方案治疗运动员已确诊的缺铁性贫血。最佳做法是什么？",options:["独立开具高剂量方案","与医生/营养师协作并遵守执业边界","忽略诊断并增加体能训练"],explanation:"确诊缺乏与治疗剂量属于合格医疗/营养专业人员范围；教练负责支持既定计划。"}),

  q("pd07","实践应用","program-design","分析","Ch. 18 · Chinese bank coverage: needs analysis",
    {prompt:"A soccer midfielder needs repeated high-speed running and change-of-direction ability. Which program choice best follows the needs analysis?",options:["Only slow single-joint training","✓ Combine strength/power, repeated-sprint exposure, and planned deceleration work","Train only maximal-duration steady cardio"],explanation:"The program should reflect the sport's force, speed, metabolic, and movement demands while accounting for the athlete."},
    {prompt:"足球中场需要反复高速跑和变向能力。哪种计划最符合需求分析？",options:["只做慢速单关节训练","结合力量/功率、重复冲刺与计划性减速训练","只练最长时长稳态有氧"],explanation:"计划应反映项目的力量、速度、代谢和动作需求，同时考虑运动员特征。"}),
  q("pd08","实践应用","program-design","应用","Ch. 18 · English bank coverage: exercise order",
    {prompt:"A session contains hang cleans, back squats, rows, and biceps curls. Best general order?",options:["Curls → rows → squats → cleans","✓ Hang cleans → back squats → rows → curls","Rows → curls → cleans → squats"],explanation:"High-skill power exercise comes first, followed by core multijoint strength work and then assistance exercises."},
    {prompt:"一堂课包含悬垂高翻、后蹲、划船和弯举。一般最合理的顺序是？",options:["弯举 → 划船 → 后蹲 → 高翻","悬垂高翻 → 后蹲 → 划船 → 弯举","划船 → 弯举 → 高翻 → 后蹲"],explanation:"高技术功率动作优先，其次是核心多关节力量动作，再到辅助动作。"}),
  q("pd09","实践应用","program-design","分析","Ch. 19 · note-bank coverage: plyometric readiness",
    {prompt:"An athlete cannot land a low jump with aligned hips, knees, and ankles. What is the best next plyometric prescription?",options:["Increase box height","Add weighted depth jumps","✓ Regress the landing task and build eccentric control before intensity"],explanation:"Landing competency and force absorption are prerequisites; increasing intensity would add risk without fixing the limiter."},
    {prompt:"运动员无法在低跳中保持髋、膝、踝对齐落地。下一步增强式处方是什么？",options:["增加跳箱高度","增加负重深跳","降低落地任务难度并先建立离心控制"],explanation:"落地能力和吸收力量是前提；提高强度只会增加风险，不能解决限制因素。"}),
  q("pd10","实践应用","program-design","应用","Ch. 20 · official-practice coverage: speed",
    {prompt:"To train maximum-velocity mechanics, when should the fastest sprint work usually appear?",options:["After exhaustive conditioning","✓ Early in the session after a specific warm-up, with full recovery","Immediately after high-volume leg failure sets"],explanation:"Maximum-speed practice requires high neural quality and low fatigue, so it is placed early with substantial recovery."},
    {prompt:"训练最大速度技术时，最快冲刺一般应安排在什么时候？",options:["力竭体能训练之后","专项热身后较早安排，并充分恢复","大量腿部力竭组之后立即进行"],explanation:"最大速度训练需要高神经质量和低疲劳，因此应较早安排并充分恢复。"}),
  q("pd11","实践应用","program-design","分析","Ch. 21 · English bank coverage: interval prescription",
    {prompt:"A runner's intervals repeatedly slow far below target despite maximal effort. Best first programming adjustment?",options:["Add more intervals","✓ Reduce repetition duration or volume and/or lengthen recovery to preserve the intended quality","Remove every recovery period"],explanation:"When output no longer matches the target zone, adjust work or recovery so the session trains the intended quality."},
    {prompt:"跑者的间歇速度反复远低于目标，尽管已经全力。最好的首次调整是什么？",options:["增加更多间歇","缩短单次时长或总量，并/或延长恢复以保护目标质量","取消所有恢复"],explanation:"当输出不再符合目标区间时，应调整做功或恢复，让训练仍然刺激预期能力。"}),
  q("pd12","实践应用","program-design","分析","Ch. 22 · note-bank coverage: periodization",
    {prompt:"Ten days before a key competition, fitness is adequate but fatigue is masking performance. Best broad strategy?",options:["Sharply increase volume","Stop all training","✓ Reduce volume while retaining selected intensity and technical quality"],explanation:"A taper reduces accumulated fatigue while maintaining the stimuli and skill needed to express fitness."},
    {prompt:"关键比赛前十天，体能足够但疲劳掩盖表现。总体最佳策略是什么？",options:["大幅增加训练量","完全停止训练","降低训练量，同时保留选择性的强度和技术质量"],explanation:"减量通过降低累积疲劳，同时保留表达体能所需的刺激与技能。"}),

  q("et07","实践应用","exercise-technique","应用","Ch. 15 · Chinese bank coverage: warm-up",
    {prompt:"Which warm-up sequence best prepares an athlete for high-speed sprinting?",options:["Long passive stretching only","✓ Raise temperature, mobilize, activate, then perform progressive sprint-specific efforts","Begin with an all-out sprint while cold"],explanation:"A RAMP-style sequence progresses from general readiness to the speed and force pattern required by the task."},
    {prompt:"哪种热身顺序最适合高速冲刺？",options:["只做长时间被动拉伸","升温、活动、激活，再逐级进行冲刺专项练习","身体冷时立即全力冲刺"],explanation:"RAMP 式顺序从一般准备逐步过渡到任务所需的速度与产力模式。"}),
  q("et08","实践应用","exercise-technique","分析","Ch. 16 · official-practice coverage: spotting",
    {prompt:"During a bench press liftoff, what should the spotter do first?",options:["Pull the bar abruptly without communication","✓ Confirm the lifter's signal and assist only enough to position the bar over the shoulders","Release the bar before it clears the hooks"],explanation:"A coordinated liftoff protects shoulder position and preserves the athlete's setup; assistance should be predictable and minimal."},
    {prompt:"卧推出杠时，保护者首先应该做什么？",options:["不沟通就突然拉杠","确认运动员信号，只提供足够帮助把杠移到肩上方","杠尚未越过挂钩就松手"],explanation:"协调出杠可保护肩部位置并维持设置；帮助应可预测且仅限必要程度。"}),
  q("et09","实践应用","exercise-technique","应用","Ch. 16 · English bank coverage: squat",
    {prompt:"A lifter's heels rise and trunk collapses early in a squat. Which regression best preserves the pattern while reducing demand?",options:["Add load to force balance","✓ Reduce load and use a controlled range where the whole foot and trunk position are maintained","Increase descent speed"],explanation:"Regress load or range to restore stable foot pressure and trunk control, then progressively regain depth."},
    {prompt:"深蹲时运动员脚跟抬起、躯干过早塌陷。哪种退阶最能保留动作模式并降低需求？",options:["加重以迫使平衡","减重并在能保持全脚掌与躯干位置的幅度内控制动作","加快下降速度"],explanation:"先降低负荷或幅度，恢复稳定脚底压力与躯干控制，再逐步增加深度。"}),
  q("et10","实践应用","exercise-technique","分析","Ch. 16 · note-bank coverage: deadlift",
    {prompt:"In a deadlift, the bar drifts several centimeters forward at knee height. What mechanical consequence is most direct?",options:["The external moment arm decreases","✓ Hip and spinal extensor torque demand increases","Gravity stops acting vertically"],explanation:"Forward bar drift lengthens the horizontal distance to key joint axes, increasing external torque and muscular demand."},
    {prompt:"硬拉到膝部高度时，杠铃向前漂移数厘米。最直接的力学后果是什么？",options:["外部力臂减小","髋与脊柱伸肌力矩需求增加","重力不再垂直作用"],explanation:"杠铃前移增加其与关键关节轴的水平距离，从而提高外部力矩和肌肉需求。"}),
  q("et11","实践应用","exercise-technique","应用","Ch. 17 · Chinese bank coverage: kettlebell",
    {prompt:"For a kettlebell swing intended as a hip-power exercise, which cue best supports the goal?",options:["Squat slowly and raise the bell with the arms","✓ Drive the hips rapidly and let the arms guide the bell","Lean backward at the top"],explanation:"The swing is a ballistic hip-hinge pattern; hip extension supplies the impulse while the arms mainly connect and guide."},
    {prompt:"以髋部功率为目标的壶铃摆动，哪条提示最合适？",options:["慢慢下蹲并用手臂抬铃","快速伸髋，让手臂只引导壶铃","顶端向后仰"],explanation:"壶铃摆动是弹道式髋铰链；伸髋提供冲量，手臂主要连接并引导。"}),
  q("et12","实践应用","exercise-technique","分析","Ch. 20 · English bank coverage: change of direction",
    {prompt:"An athlete enters a planned cut too upright and cannot decelerate. Which cue best addresses the first priority?",options:["Take a longer final braking step","✓ Lower the center of mass and use earlier, shorter braking contacts","Keep the knees locked"],explanation:"Earlier braking and a lower center of mass improve control of momentum before the directional change."},
    {prompt:"运动员进入预定变向时身体过直且无法减速。哪条提示最先解决问题？",options:["最后一步迈得更长","降低重心并更早使用较短制动步","保持膝关节锁死"],explanation:"提前制动和降低重心能在改变方向前更好地控制动量。"}),

  q("im07","实践应用","implementation","记忆","Ch. 13 · Chinese bank coverage: validity",
    {prompt:"A test consistently measures the wrong physical quality. Which statement is correct?",options:["It is valid because it is consistent","✓ It may be reliable but lacks validity for the intended construct","It is neither reliable nor measurable"],explanation:"Reliability is consistency; a consistent measure can still fail to represent the intended quality."},
    {prompt:"某测试能稳定测量，但测到的是错误的身体能力。哪项正确？",options:["只要稳定就有效","它可能可靠，但对目标构念缺乏效度","它既不可靠也不可测"],explanation:"信度是一致性；测量可以很稳定，却仍不能代表目标能力。"}),
  q("im08","实践应用","implementation","应用","Ch. 13 · English bank coverage: test order",
    {prompt:"Which same-day test order best protects results?",options:["Aerobic capacity → 1RM → agility","✓ Nonfatiguing measure → agility → power/strength → sprint → anaerobic/aerobic capacity","Local endurance → body mass → vertical jump"],explanation:"Low-fatigue and highly fatigue-sensitive speed/power measures precede fatiguing capacity tests."},
    {prompt:"哪种同日测试顺序最能保护结果质量？",options:["有氧能力 → 1RM → 敏捷","非疲劳指标 → 敏捷 → 功率/力量 → 冲刺 → 无氧/有氧能力","局部耐力 → 体重 → 垂直跳"],explanation:"低疲劳指标与最易受疲劳影响的速度/功率测试应先于能力类疲劳测试。"}),
  q("im09","实践应用","implementation","分析","Ch. 14 · official-practice coverage: measurement error",
    {prompt:"An athlete's jump improves 1 cm, but the test's typical error is 2 cm. Best interpretation?",options:["The improvement is definitely real","The athlete definitely declined","✓ The change may be measurement noise; collect more standardized evidence"],explanation:"A change smaller than expected measurement error should not trigger a confident performance conclusion."},
    {prompt:"运动员跳高提高 1 cm，但测试典型误差为 2 cm。最佳解释是什么？",options:["提升一定真实","运动员一定退步","变化可能是测量噪声，应收集更多标准化证据"],explanation:"小于预期测量误差的变化，不应支持确定的表现结论。"}),
  q("im10","实践应用","implementation","应用","Ch. 14 · note-bank coverage: relative strength",
    {prompt:"Athlete A squats 180 kg at 90 kg body mass; Athlete B squats 160 kg at 70 kg. Who has greater relative strength?",options:["Athlete A","✓ Athlete B","They are equal"],explanation:"A: 180/90 = 2.0; B: 160/70 ≈ 2.29. Athlete B has the higher body-mass-normalized score."},
    {prompt:"A 运动员 90 kg 体重深蹲 180 kg；B 运动员 70 kg 体重深蹲 160 kg。谁的相对力量更高？",options:["A 运动员","B 运动员","相同"],explanation:"A：180/90 = 2.0；B：160/70 ≈ 2.29，因此 B 的体重标准化得分更高。"}),
  q("im11","实践应用","implementation","分析","Ch. 24 · Chinese bank coverage: monitoring",
    {prompt:"Readiness score is low today, but warm-up performance is normal and the athlete reports a late bedtime only. Best decision?",options:["Diagnose overtraining syndrome","Cancel the entire week","✓ Use context, monitor the session, and make only the smallest needed adjustment"],explanation:"One score is not a diagnosis. Combine trend, context, symptoms, and performance before changing training."},
    {prompt:"今天准备度得分低，但热身表现正常，运动员只报告昨晚睡得晚。最佳决策是什么？",options:["诊断过度训练综合征","取消整周训练","结合情境监测训练，只做最小必要调整"],explanation:"单一得分不能用于诊断。应结合趋势、情境、症状与表现后再调整。"}),
  q("im12","实践应用","implementation","应用","Ch. 23 · English bank coverage: return to sport",
    {prompt:"During reconditioning, an athlete meets time-based milestones but fails repeated deceleration criteria. Next step?",options:["Clear full competition because enough days passed","✓ Continue targeted reconditioning and reassess the failed criterion with the medical team","Ignore deceleration because strength is normal"],explanation:"Return progression is criteria-based and interdisciplinary; elapsed time alone does not prove readiness."},
    {prompt:"再训练中，运动员满足时间节点，但未通过重复减速标准。下一步是什么？",options:["时间够了就直接恢复比赛","继续针对性再训练，并与医疗团队复测失败标准","力量正常就忽略减速"],explanation:"重返进程应基于标准并跨专业协作；经过足够时间不等于已准备好。"}),

  q("oa07","实践应用","organization","应用","Ch. 25 · Chinese bank coverage: layout",
    {prompt:"Where should highly supervised, high-risk lifting stations generally be placed?",options:["Behind opaque storage walls","✓ Where staff have clear sightlines and emergency access remains open","In the narrowest traffic corridor"],explanation:"Visibility, clearance, and emergency access support supervision and reduce collision or response delays."},
    {prompt:"需要高度监督、风险较高的举重站一般应放在哪里？",options:["不透明储藏墙后","工作人员视线清楚且应急通道保持开放的位置","最狭窄的通行走廊"],explanation:"视野、间距和应急通行能提高监督质量并减少碰撞或响应延迟。"}),
  q("oa08","实践应用","organization","分析","Ch. 25 · English bank coverage: traffic flow",
    {prompt:"Athletes repeatedly carry plates across a sprint lane to reach storage. Best systems fix?",options:["Post a warning but keep the layout","✓ Relocate storage to reduce crossing traffic and enforce a clear return route","Make athletes move faster across the lane"],explanation:"Engineering and layout controls remove recurring exposure more reliably than warnings alone."},
    {prompt:"运动员归还杠铃片时必须反复横穿冲刺跑道。最佳系统性解决方案是什么？",options:["只贴警告但不改布局","调整储存位置以减少交叉动线，并执行明确归还路线","要求运动员更快穿过跑道"],explanation:"工程与布局控制比单纯警告更可靠地消除重复暴露。"}),
  q("oa09","实践应用","organization","记忆","Ch. 26 · Chinese bank coverage: negligence",
    {prompt:"Which four elements generally must be established in a negligence claim?",options:["Intent, profit, contract, publicity","✓ Duty, breach, causation, and damages","Speed, strength, power, and endurance"],explanation:"Negligence analysis generally asks whether a duty existed, was breached, caused the harm, and produced damages."},
    {prompt:"过失主张通常需要证明哪四项要素？",options:["故意、利润、合同、宣传","义务、违约、因果关系与损害","速度、力量、功率与耐力"],explanation:"过失分析通常判断是否存在义务、是否违反、是否导致伤害以及是否产生损害。"}),
  q("oa10","实践应用","organization","应用","Ch. 26 · official-practice coverage: EAP",
    {prompt:"What is the best way to verify that an Emergency Action Plan works?",options:["Store it in a locked office","✓ Rehearse realistic scenarios, time critical actions, and revise identified gaps","Assume certified staff will improvise"],explanation:"A written plan becomes operational through accessible roles, rehearsal, timing, documentation, and improvement."},
    {prompt:"验证应急行动计划有效性的最佳方法是什么？",options:["把它锁在办公室","演练真实情境、计时关键行动并修订暴露问题","假设持证人员会临场发挥"],explanation:"书面计划必须通过明确角色、演练、计时、记录与改进才能真正运行。"}),
  q("oa11","实践应用","organization","分析","Ch. 26 · English bank coverage: documentation",
    {prompt:"After an incident, which documentation practice is best?",options:["Add guesses about blame","Delete inconvenient details","✓ Record timely, objective observations and actions according to policy"],explanation:"Incident records should be prompt, factual, complete, secure, and consistent with organizational procedure."},
    {prompt:"事件发生后，哪种记录方式最好？",options:["加入对责任的猜测","删除不利细节","按制度及时、客观记录观察与行动"],explanation:"事件记录应及时、客观、完整、安全，并符合组织流程。"}),
  q("oa12","实践应用","organization","应用","Ch. 26 · note-bank coverage: scope and staff",
    {prompt:"A newly hired coach lacks current CPR/AED certification. What should the director do?",options:["Allow unsupervised sessions temporarily","✓ Restrict duties until credentials are current and document verification","Ask athletes to assume the risk"],explanation:"Credential verification and role restriction are basic risk-management and staffing responsibilities."},
    {prompt:"新聘教练没有有效 CPR/AED 认证。主管应如何处理？",options:["暂时允许其独立带课","在证书有效前限制职责并记录核验","让运动员自行承担风险"],explanation:"核验资质与限制职责是基本风险管理和人员管理责任。"}),
];
